version: '3.9'

services:
  apache2:
    hostname: apache2
    build:
      context: ./apache2
      args:
        LISTEN_PORT: "8181"
    container_name: apache2
  rails:
    hostname: rails
    build:
      context: ./rails
      args:
        RUBY_VERSION: "3.0.2"
        NODE_VERSION: "14.17.5"
        YARN_VERSION: "1.22.11"
    container_name: rails
    environment:
      LISTEN_PORT: 3000
      ENVIRONMENT: development
    ports:
      - "3000:3000"
    volumes:
      - ${PWD}/rails/files/database.yml:/opt/app/config/database.yml:ro
  postgresql:
    hostname: postgresql
    build:
      context: ./postgresql
      args:
        VERSION: "13.4"
    container_name: postgresql
    environment:
      LISTEN_PORT: "5432"
      PG_DATABASE: "rails"
      PG_USERNAME: "rails"
    volumes:
      - ${PWD}/postgresql/files/pg_hba.conf:/opt/app/pg_hba.conf:ro
      - ${PWD}/postgresql/files/postgresql.conf:/opt/app/postgresql.conf:ro
  redis:
    hostname: redis
    build:
      context: ./redis
      args:
        VERSION: "6.2.5"
    container_name: redis
    environment:
      LISTEN_PORT: "6379"
      DB_FILENAME: "example.rdb"
  requester:
    hostname: requester
    build:
      context: ./requester
    container_name: requester
    environment:
      REQ_HOST: "apache2"
      REQ_PORT: "8181"